allECOS = [
    # AIRSIDE METHODS
    {'title':'Leaking Valves',
    'link': 'LeakingValves',
    'type': 'Airside Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title':'Economizer',
    'link': 'Economizer',
    'type': 'Airside Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title':'Supply Air Temperature Reset',
    'link': 'SATReset',
    'type': 'Airside Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title':'CAV to VAV Conversion',
    'link': 'CAV2VAV',
    'type': 'Airside Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title':'Static Pressure Reset',
    'link': 'StaticPressureReset',
    'type': 'Airside Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title':'Demand Control Ventilation',
    'link': 'DCV',
    'type': 'Airside Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title':'Outdoor Air Damper Control',
    'link': 'DamperControl',
    'type': 'Airside Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title':'Unoccupied Temperature Setback',
    'link': 'UnoccTempSetback',
    'type': 'Airside Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title':'Mixed Air Temperature Reset',
    'link': 'MATReset',
    'type': 'Airside Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title':'Energy Efficient Motor Replacement',
    'link': 'MotorReplacement',
    'type': 'Airside Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    },
    # BOILER METHODS
    {'title':'Leaking Valves',
    'link': 'LeakingValves',
    'type': 'Boiler Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title':'Hot Water Reset',
    'link': 'HotWaterReset',
    'type': 'Boiler Energy Conservation Methods',
    'attributes':[],
    'assumptions': [],
    }, 
    {'title':'Stack heat recovery',
    'link': 'StackHeatRecovery',
    'type': 'Boiler Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title':'Steam Trap Replacments',
    'link': 'SteamTrapReplacement',
    'type': 'Boiler Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title':'Variable Volume Hot Water Pumping',
    'link': 'VariableVolumePump',
    'type': 'Boiler Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title':'Blowdown Heat Recovery',
    'link': 'BlowdownHeatRecovery',
    'type': 'Boiler Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title':'(Condensing) Boiler Replacement',
    'link': 'BoilerReplacement',
    'type': 'Boiler Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title':'CoGeneration',
    'link': 'CoGen',
    'type': 'Boiler Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    },
    # CHILLER METHODS
    {'title':'Leaking Valves',
    'link': 'LeakingValves',
    'type': 'Chiller Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title':'Chilled Water Reset',
    'link': 'ChilledWaterReset',
    'type': 'Chiller Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title':'Condenser water relief', 
    'link': 'CondenserWaterRelief',
    'type': 'Chiller Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title': 'Cooling Tower VFD',
    'link': 'CoolingTowerVFD',
    'type': 'Chiller Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    },
    {'title': 'Variable Volume Chilled Water Pumping',
    'link': 'VVChilledWater',
    'type': 'Chiller Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    },
    {'title': 'Chiller Replacement',
    'link': 'ChillerReplacement',
    'type': 'Chiller Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    },
    {'title': 'Tower Filtration',
    'link': 'TowerFiltration',
    'type': 'Chiller Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    },
    # MISC METHODS
    {'title': 'Piping Insulation', 
    'link': 'PipingInsulation',
    'type': 'Miscellaneous Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    },
    {'title': 'LED Lighting Retrofits',
    'link': 'LightingRetrofit',
    'type': 'Miscellaneous Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    },
    {'title': 'Lighting Occupancy Sensors', 
    'link': 'LightingOccupancy',
    'type': 'Miscellaneous Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    },
    {'title': 'Power Factor Correction',
    'link': 'PFCorrection',
    'type': 'Miscellaneous Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    },
    {'title': 'Destratifying Fans',
    'link': 'DestratifyingFan',
    'type': 'Miscellaneous Energy Conservation Methods',
    'attributes': ['supplyAirVolume', 'ceilingTemp', 'floorTemp', 'existingAvgTemp', 'hoursOp', 'daysOp', 'hoursPerHtgSeason'],
    'assumptions':['htgSysEfficiency', 'motorLoadFactor', 'motorEfficiency', 'ceilingFanHP'],
    },
    {'title': 'Peak Demand Limiting',
    'link': 'PeakDemandLimiting',
    'type': 'Miscellaneous Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    },
    {'title': 'Window Replacement',
    'link': 'WindowReplacement',
    'type': 'Miscellaneous Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }
]