allECOS = [
    # AIRSIDE METHODS
    # {'title':'Leaking Valves',
    # 'link': 'LeakingValves',
    # 'type': 'Airside Energy Conservation Methods',
    # 'attributes':[],
    # 'assumptions':[],
    # }, 
    {'title':'Dry Bulb Economizer',
    'link': 'DryBulbEconomizer',
    'type': 'Airside Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title':'Enthalpy Economizer',
    'link': 'EnthalpyEconomizer',
    'type': 'Airside Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title':'Supply Air Temperature Reset',
    'link': 'SATReset',
    'type': 'Airside Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title':'CAV to VAV Conversion',
    'link': 'CAV2VAV',
    'type': 'Airside Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title':'Static Pressure Reset',
    'link': 'StaticPressureReset',
    'type': 'Airside Energy Conservation Methods',
    'attributes':['sysPressure', 'newSysPressure', 'fanEfficiency', 'motorEfficiency', 'fanVolume', 'newFanVolume', 'hoursOfUse'],
    'assumptions':[],
    }, 
    {'title':'Demand Control Ventilation',
    'link': 'DCV',
    'type': 'Airside Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title':'Outdoor Air Damper Control',
    'link': 'DamperControl',
    'type': 'Airside Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title':'Unoccupied Temperature Setback',
    'link': 'UnoccTempSetback',
    'type': 'Airside Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title':'Mixed Air Temperature Reset',
    'link': 'MATReset',
    'type': 'Airside Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title':'Energy Efficient Motor Replacement',
    'link': 'MotorReplacement',
    'type': 'Airside Energy Conservation Methods',
    'attributes':['motorSize', 'motorEfficiency', 'motorVoltage', 'loadRPM', 'hoursOfUse', 'motorKW', 'newMotorSize', 'newMotorEfficiency', 'newMotorVoltage', 'newLoadRPM', 'newHoursOfUse', 'newMotorKW'],
    'assumptions':['existingMotorLoadFactor', 'newMotorLoadFactor', 'powerFactor', 'demandUseFactor', 'peakLoadMonths'],
    },
    # BOILER METHODS
    # {'title':'Leaking Valves',
    # 'link': 'LeakingValves',
    # 'type': 'Boiler Energy Conservation Methods',
    # 'attributes':[],
    # 'assumptions':[],
    # }, 
    {'title':'Hot Water Reset',
    'link': 'HotWaterReset',
    'type': 'Boiler Energy Conservation Methods',
    'attributes':['binhours', 'OATemp', 'boilerPeakLoad', 'boilerEfficency', 'designHotWaterSupplyTemp', 'designIndoorAirTemp', 'designOutdoorAirTemp', 'hotWaterReset', 'minimumBoilerLoad'],
    'assumptions': ['resetFactor', 'heatingSeasonInitiate'],
    }, 
    {'title':'Stack heat recovery',
    'link': 'StackHeatRecovery',
    'type': 'Boiler Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title':'Steam Trap Replacments',
    'link': 'SteamTrapReplacement',
    'type': 'Boiler Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title':'Variable Volume Hot Water Pumping',
    'link': 'VariableVolumePump',
    'type': 'Boiler Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title':'Blowdown Heat Recovery',
    'link': 'BlowdownHeatRecovery',
    'type': 'Boiler Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title':'(Condensing) Boiler Replacement',
    'link': 'BoilerReplacement',
    'type': 'Boiler Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title':'CoGeneration',
    'link': 'CoGen',
    'type': 'Boiler Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    },
    # CHILLER METHODS
    # {'title':'Leaking Valves',
    # 'link': 'LeakingValves',
    # 'type': 'Chiller Energy Conservation Methods',
    # 'attributes':[],
    # 'assumptions':[],
    # }, 
    {'title':'Chilled Water Reset',
    'link': 'ChilledWaterReset',
    'type': 'Chiller Energy Conservation Methods',
    'attributes':['binhours', 'OATemp', 'chillerPeakLoad', 'chillerEfficiency', 'chilledWaterReset', 'resetFactor', 'outsideAirInitiates', 'minimumChillerLoad', 'designOATemp'],
    'assumptions':[],
    }, 
    {'title':'Condenser water relief', 
    'link': 'CondenserWaterRelief',
    'type': 'Chiller Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    }, 
    {'title': 'Cooling Tower VFD',
    'link': 'CoolingTowerVFD',
    'type': 'Chiller Energy Conservation Methods',
    'attributes':['binhours', 'OATemp', 'motorHP', 'towerTon', 'fanType', 'fanspeed'],
    'assumptions':['motorLoading', 'motorEfficiency', 'powerReductionExponent', 'minimumVFDSpeed'],
    },
    {'title': 'Variable Volume Chilled Water Pumping',
    'link': 'VVChilledWater',
    'type': 'Chiller Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    },
    # {'title': 'Chiller Replacement',
    # 'link': 'ChillerReplacement',
    # 'type': 'Chiller Energy Conservation Methods',
    # 'attributes':[],
    # 'assumptions':[],
    # },
    {'title': 'Tower Filtration',
    'link': 'TowerFiltration',
    'type': 'Chiller Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    },
    # MISC METHODS
    {'title': 'Piping Insulation', 
    'link': 'PipingInsulation',
    'type': 'Miscellaneous Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    },
    # {'title': 'LED Lighting Retrofits',
    # 'link': 'LightingRetrofit',
    # 'type': 'Miscellaneous Energy Conservation Methods',
    # 'attributes':[],
    # 'assumptions':[],
    # },
    {'title': 'Lighting Occupancy Sensors', 
    'link': 'LightingOccupancy',
    'type': 'Miscellaneous Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    },
    {'title': 'Power Factor Correction',
    'link': 'PFCorrection',
    'type': 'Miscellaneous Energy Conservation Methods',
    'attributes':['powerKW', 'powerKVAR', 'powerKVA', 'powerFactorKVARCharge', 'powerFactorKVACharge'],
    'assumptions':['powerFactorChargeType', 'minimumPFPenalty', 'proposedCorrection', 'existingMultiplier', 'existingAdjustment'],
    },
    {'title': 'Destratifying Fans',
    'link': 'DestratifyingFan',
    'type': 'Miscellaneous Energy Conservation Methods',
    'attributes': ['supplyAirVolume', 'ceilingTemp', 'floorTemp', 'existingAvgTemp', 'hoursOp', 'daysOp', 'hoursPerHtgSeason'],
    'assumptions':['htgSysEfficiency', 'motorLoadFactor', 'motorEfficiency', 'ceilingFanHP'],
    },
    {'title': 'Peak Demand Limiting',
    'link': 'PeakDemandLimiting',
    'type': 'Miscellaneous Energy Conservation Methods',
    'attributes':[],
    'assumptions':[],
    },
    # {'title': 'Window Replacement',
    # 'link': 'WindowReplacement',
    # 'type': 'Miscellaneous Energy Conservation Methods',
    # 'attributes':[],
    # 'assumptions':[],
    # }
]